---
# Pulsar Express - Lightweight Web UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-express
  namespace: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar-express
  template:
    metadata:
      labels:
        app: pulsar-express
    spec:
      containers:
      - name: pulsar-express
        image: bbonnin/pulsar-express:latest
        ports:
        - containerPort: 3000
        env:
        - name: PULSAR_URL
          value: "http://pulsar-broker.pulsar.svc.cluster.local:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
---
# Pulsar Express Service
apiVersion: v1
kind: Service
metadata:
  name: pulsar-express
  namespace: pulsar
spec:
  type: NodePort
  selector:
    app: pulsar-express
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    name: http