apiVersion: v1
kind: Namespace
metadata:
  name: woodpecker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: woodpecker
  namespace: woodpecker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: woodpecker
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: woodpecker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: woodpecker
subjects:
- kind: ServiceAccount
  name: woodpecker
  namespace: woodpecker