apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server
  namespace: woodpecker
type: Opaque
stringData:
  # Generate these values:
  # WOODPECKER_AGENT_SECRET: openssl rand -hex 32
  WOODPECKER_AGENT_SECRET: "0388131287819b2e2af887df742cc0310f2c823f855dd57514d4a175f2862276"
  
  # GitHub OAuth App credentials
  # Create at: https://github.com/settings/applications/new
  # Homepage URL: https://ci.playablestories.ai
  # Callback URL: https://ci.playablestories.ai/authorize
  WOODPECKER_GITHUB_CLIENT: "Ov23liSduSken4EmvUMe"
  WOODPECKER_GITHUB_SECRET: "fce0f1ee5aab4b262120659bcf75a34a631eee5d"
  
  # Webhook secret for validating GitHub webhooks
  WOODPECKER_WEBHOOK_SECRET: "0388131287819b2e2af887df742cc0310f2c823f855dd57514d4a175f2862276"
---
apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-agent
  namespace: woodpecker
type: Opaque
stringData:
  # Must match server secret
  WOODPECKER_AGENT_SECRET: "0388131287819b2e2af887df742cc0310f2c823f855dd57514d4a175f2862276"