---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-gpu
  namespace: gpu-workloads
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    name: jupyter
  selector:
    app: jupyter-gpu
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyter-gpu
  namespace: gpu-workloads
spec:
  serviceName: jupyter-gpu
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-gpu
  template:
    metadata:
      labels:
        app: jupyter-gpu
    spec:
      containers:
      - name: jupyter
        image: tensorflow/tensorflow:latest-gpu-jupyter
        ports:
        - containerPort: 8888
          name: jupyter
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: JUPYTER_TOKEN
          value: "changeme"  # Change this!
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 16Gi
            cpu: 8
          requests:
            nvidia.com/gpu: 1
            memory: 8Gi
            cpu: 4
        volumeMounts:
        - name: notebook-storage
          mountPath: /tf/notebooks
        - name: models-storage
          mountPath: /tf/models
  volumeClaimTemplates:
  - metadata:
      name: notebook-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gpu-storage
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: models-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gpu-storage
      resources:
        requests:
          storage: 500Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter-gpu-ingress
  namespace: gpu-workloads
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: jupyter.example.com  # Change this!
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jupyter-gpu
            port:
              number: 8888