---
# Registry UI for MicroK8s registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: container-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
      - name: registry-ui
        image: joxit/docker-registry-ui:latest
        ports:
        - containerPort: 80
        env:
        - name: REGISTRY_URL
          value: http://registry:5000
        - name: DELETE_IMAGES
          value: "true"
        - name: REGISTRY_TITLE
          value: "MicroK8s Local Registry"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: container-registry
spec:
  type: NodePort
  selector:
    app: registry-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32080