apiVersion: v1
kind: Service
metadata:
  name: playablestories-api
  namespace: development
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 192.168.0.118:32000/mmorpg-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes,dev,no-auth"
        - name: SERVER_PORT
          value: "8090"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://narrative_user:0qJXBckS6huZWJtTgBEEHd0dc%2FuE9RBkbH7sRx11vpg%3D@mongodb-client.mongodb.svc.cluster.local:27017/narrative_world_system?authSource=admin&replicaSet=rs0"
        - name: JWT_SECRET
          value: "dGhpcy1pcy1hLXRlc3Qtb25seS1zZWNyZXQtZm9yLWRldmVsb3BtZW50LXVzZS1vbmx5"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 5
---
# Production deployment
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8090
    targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 192.168.0.118:32000/mmorpg-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes,prod"
        - name: SERVER_PORT
          value: "8090"
        - name: MONGODB_URI
          value: "mongodb://mongodb.mongodb.svc.cluster.local:27017/mmorpg-prod"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 5